In [1]:
from apps.logic.getHandler import getPhrases
from apps.logic.getHandler import runModel

print("Importing NER_Spacy: ")
from apps.nlp_core.Models.spacy import NER_Spacy

print("Importing Article parser:")
from apps.nlp_core.SentimentTracker.index import InitialArticleParser

print("importing DeepMoji: ")
from apps.nlp_core.Models.deepmoji import DeepMoji

Importing NER_Spacy: 
Importing Article parser:
C:\Users\EJgom\Documents\S\A\NLP_RestAPI\nlp_api\apps\nlp_core\DeepMoji
importing DeepMoji: 


In [7]:
TEST_SENTENCES = [u'I love mom\'s cooking',
                  u'I love how you never reply back..',
                  u'I love cruising with my homies',
                  u'I love messing with yo mind!!',
                  u'I love you and now you\'re just gone..',
                  u'This is shit',
                  u'This is the shit',
                  u'i am disgusted']
tennis_opinion = "The start of a new tennis season prompts an inevitable question: Could this be Roger Federer’s last year on the court. It is a possibility that fills Federer partisans with something approaching existential dread — fear that the un-Federered life might not be worth living, or at least won’t be nearly as pleasurable. Federer is 38, and although he is still at the top of the game — he is currently ranked third — and a threat to win any tournament that he enters, retirement surely can’t be too far off now. But as the 2020 season gets underway, Federer fans have something else to fret about. At some point this year, Rafael Nadal is likely to equal and maybe even surpass Federer’s foremost achievement, a record 20 Grand Slam singles titles. Nadal’s victory at last year’s United States Open was his 19th major title. He will get his first chance to reach 20 at the Australian Open in Melbourne, which starts this week. If not there, and assuming Federer doesn’t win the Australian, Nadal will probably tie the record at the French Open in June. Nadal on clay in Paris remains the surest money in sports — he has captured that Grand Slam a dozen times. Because he is about five years younger than Federer, it seems almost certain now that he will finish his career with more majors, which will arguably give him a stronger claim to being the “greatest (male player) of all time” — the GOAT, to use the popular acronym. That is not how this story was supposed to end. Or maybe we’ve been telling ourselves the wrong story."
TENNIS_SENTENCES=tennis_opinion.split(".")

SENTIMENT = [u'Erick is the best. Erick can learn anything he wants. Erick is sometimes a little forgetful',
            u'Erick can learn anything he wants',
             u'Erick is sometimes a little forgetful'
            ]

In [11]:
deepmoji= DeepMoji()
deepmoji.initialize()

input_shape:  (None, 30, 2304)
weights:   []
updated weights [<tf.Variable 'attlayer/attlayer_W:0' shape=(2304, 1) dtype=float32, numpy=
array([[-0.03540816],
       [ 0.03582224],
       [ 0.04098945],
       ...,
       [ 0.01744607],
       [-0.00649999],
       [-0.03066605]], dtype=float32)>]
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'list'>


In [23]:

print(deepmoji.model.layers[1])
print(deepmoji.model.layers[1].input_shape)
print(deepmoji.model.layers[1].output_shape)

print(deepmoji.model.layers[1].embeddings_regularizer)

print(deepmoji.model.layers[1].embeddings_initializer)

(None, 30)
(None, 30, 256)


In [8]:
i = InitialArticleParser()

In [10]:
j = runModel(i,SENTIMENT,test=True)

-------         IS THE MODEL INITIALIZED:     True
[ 6 20 26 15 25]
[20 25 12  6  8]
[26  9 15  6 50]
[26  9 15  6 50]
[26  9 15  6 50]
[26  9 15 50 13]
[26  9 15 50 13]
[26  9 15 50 13]
[26  9 15 50 13]
[20 25 12 22 62]
[20 25 12 22 62]


In [14]:
import spacy
nlp = spacy.load('en_core_web_sm')
from spacy import displacy

In [15]:
doc = nlp(SENTIMENT[0])

In [40]:
for count,sent in enumerate(doc.sents):
    print(count,sent)

0 Erick is the best.
1 Erick can learn anything he wants.
2 Erick is sometimes a little forgetful


<class 'NoneType'>
